### ISSUE TITLE
No installation or compilation instructions

### ISSUE THREAD

**Issue by gatlinnewhouse** [jakoch/csgo-cli#6]
If this were built for linux I would probably be able to figure this out but Windows 10 is not a strength of mine. How is this installed or compiled?

**Comment by jakoch** [comment]
Hey Gatlin!

I've added installation instructions to the readme: https://github.com/jakoch/csgo-cli#installation

Does this answer your question?

##### How is this compiled?
Well, it's all there... 
This is a CMake project, so referencing: [CMakeLists.txt](https://github.com/jakoch/csgo-cli/blob/master/CMakeLists.txt). 
You find all commands for compilation in the [appveyor.yml](https://github.com/jakoch/csgo-cli/blob/master/appveyor.yml) file.

**Comment by gatlinnewhouse** [comment]
Thanks!
